-- Extend in-app notification types (gamification + social)
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'XP_GAIN';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'QUEST_COMPLETED';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'CHEST_READY';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'ACHIEVEMENT';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'PARTY_RAID_INVITE';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'FRIEND_REQUEST';
ALTER TYPE "UserNotificationType" ADD VALUE IF NOT EXISTS 'CARD_ASSIGNED';

-- Monthly quest period
ALTER TYPE "QuestPeriod" ADD VALUE IF NOT EXISTS 'MONTHLY';

ALTER TYPE "UserSecurityEventType" ADD VALUE IF NOT EXISTS 'ACCOUNT_DELETED';
