export declare const GAMIFICATION_ERROR_CODE: {
    readonly XP_EVENT_DAY_KEY_REQUIRED: "XP_EVENT_DAY_KEY_REQUIRED";
    readonly CHECKIN_ALREADY_DONE: "CHECKIN_ALREADY_DONE";
    readonly XP_EVENT_ALREADY_RECORDED: "XP_EVENT_ALREADY_RECORDED";
    readonly DAILY_TASK_XP_LIMIT: "DAILY_TASK_XP_LIMIT";
};
export type GamificationErrorCode = (typeof GAMIFICATION_ERROR_CODE)[keyof typeof GAMIFICATION_ERROR_CODE];
